# Generated by Django 5.1.6 on 2025-02-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='predictions',
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='fuel_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='ga_co2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='ga_nox',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='ga_pm25_brake_wear',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='ga_pm25_tire_wear',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='ga_total_energy_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='speed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
