# Generated by Django 5.1.6 on 2025-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0003_rename_timestamp_predictionlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
